import { forwardRef, type HTMLAttributes, type ReactNode } from "react";
import { warnIfMissingAccessibleName } from "../../internal/a11y.js";
import styles from "./{{componentName}}.module.css";

export interface {{componentName}}Props extends HTMLAttributes<HTMLDivElement> {
  children?: ReactNode;
}

/**
 * Generated by `foundry generate component`. The root element, prop shape,
 * and behavior here are a neutral starting point, not a finished component.
 * Pick the right semantic element (button, input, ...) for what
 * {{componentName}} does, and extend {{componentName}}Props accordingly.
 * Match the conventions the rest of the library follows: variant/size for
 * style axes, native prop names for native behavior (disabled, required,
 * ...), forwardRef always, value/defaultValue/onChange via
 * useControlledState for anything with controlled state. See Button and
 * Input for the two shapes in practice.
 */
export const {{componentName}} = forwardRef<HTMLDivElement, {{componentName}}Props>(function {{componentName}}(
  { children, className, "aria-label": ariaLabel, "aria-labelledby": ariaLabelledBy, ...rest },
  ref,
) {
  warnIfMissingAccessibleName({
    component: "{{componentName}}",
    hasAccessibleContent: Boolean(children),
    ariaLabel,
    ariaLabelledBy,
    guidance:
      'this component has no visible text and needs an accessible name. Pass aria-label="..." so assistive technology can announce what it does.',
  });

  return (
    <div {...rest} ref={ref} className={[styles.root, className].filter(Boolean).join(" ")}>
      {children}
    </div>
  );
});
