import { forwardRef, type HTMLAttributes, type ReactNode } from "react";
import { warnIfMissingAccessibleName } from "../internal/a11y.js";
import styles from "./{{componentName}}.module.css";

export interface {{componentName}}Props extends HTMLAttributes<HTMLDivElement> {
  children?: ReactNode;
}

/**
 * Generated by `foundry generate component`. The root element, prop
 * shape, and behavior here are a deliberately neutral starting point, not
 * a finished component — pick the right semantic element (button, input,
 * ...) for what {{componentName}} actually does, and extend
 * {{componentName}}Props accordingly. See docs/adr/0001 for the naming
 * conventions the rest of the library follows once you do.
 */
export const {{componentName}} = forwardRef<HTMLDivElement, {{componentName}}Props>(
  function {{componentName}}(
    { children, className, "aria-label": ariaLabel, "aria-labelledby": ariaLabelledBy, ...rest },
    ref,
  ) {
    warnIfMissingAccessibleName({
      component: "{{componentName}}",
      hasAccessibleContent: Boolean(children),
      ariaLabel,
      ariaLabelledBy,
      guidance:
        'this component has no visible text and needs an accessible name — pass aria-label="..." so assistive technology can announce what it does.',
    });

    return (
      <div {...rest} ref={ref} className={[styles.root, className].filter(Boolean).join(" ")}>
        {children}
      </div>
    );
  },
);
